name: radio_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  country_picker: ^2.0.25
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_svg_image: ^1.1.0+1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  hive_flutter: ^1.1.0
  hive_wait: ^1.0.2+2
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.3.1
  radio_player: ^1.5.1
  retrofit: ^4.1.0
  rxdart: ^0.27.7
  siri_wave: ^2.0.0+1

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  hive_generator: ^2.0.1
  http_mock_adapter: ^0.6.1
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  mocktail_image_network: ^1.1.0
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
